name: Infrastructure CI

on:
  push:
    paths:
      - infrastructure/**
      - .github/workflows/infrastructure.yaml
  pull_request:
    paths:
      - infrastructure/**
      - .github/workflows/infrastructure.yaml
  workflow_dispatch:

defaults:
  run:
    working-directory: infrastructure


jobs:
  lint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run tflint
        run: |
          tflint --init
          tflint --recursive

  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Checkov Action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: infrastructure
          framework: terraform
          quiet: true
          # skip_check: 

  readme:
    name: Terraform Docs
    runs-on: ubuntu-latest
    needs: checkov
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Render terraform docs
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: infrastructure
          output-file: README.md
          output-method: inject
          git-push: true
